# Generated by Django 4.2.1 on 2023-06-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_blood_bank_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='contact_person_name',
            field=models.CharField(default='badri', max_length=50),
        ),
    ]
