# Generated by Django 4.2.1 on 2023-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_blood_bank_contact_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='contact_person_name',
            field=models.CharField(max_length=50),
        ),
    ]
